# WorkflowAI Environment Setup Script
#!/bin/bash

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Configuration
PROJECT_DIR="$(pwd)"
ENV_FILE=".env"
SUPABASE_DIR="./supabase"
VENV_DIR="./backend/venv"

echo -e "${BLUE}🏗️  WorkflowAI 환경 설정 스크립트${NC}"
echo -e "${BLUE}=======================================${NC}"
echo ""

# Function to prompt for user input with validation
prompt_for_input() {
    local var_name=$1
    local prompt_message=$2
    local default_value=$3
    local validation_pattern=$4
    
    while true; do
        if [ ! -z "$default_value" ]; then
            echo -e "${YELLOW}$prompt_message (기본값: $default_value):${NC}"
        else
            echo -e "${YELLOW}$prompt_message:${NC}"
        fi
        
        read -r input
        
        # Use default if input is empty
        if [ -z "$input" ] && [ ! -z "$default_value" ]; then
            input=$default_value
        fi
        
        # Validate input if pattern provided
        if [ ! -z "$validation_pattern" ]; then
            if [[ $input =~ $validation_pattern ]]; then
                echo "$input"
                return 0
            else
                echo -e "${RED}❌ 잘못된 형식입니다. 다시 시도해주세요.${NC}"
                continue
            fi
        fi
        
        if [ ! -z "$input" ]; then
            echo "$input"
            return 0
        else
            echo -e "${RED}❌ 값을 입력해주세요.${NC}"
        fi
    done
}

# Function to generate secure random string
generate_secret() {
    openssl rand -hex 32
}

# Check prerequisites
echo -e "${BLUE}📋 사전 요구사항 확인 중...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js가 설치되지 않았습니다. https://nodejs.org에서 설치해주세요.${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Node.js $(node --version) 확인됨${NC}"

# Check Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3이 설치되지 않았습니다.${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Python $(python3 --version) 확인됨${NC}"

# Check Docker (optional)
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✅ Docker $(docker --version) 확인됨${NC}"
else
    echo -e "${YELLOW}⚠️  Docker가 없습니다. 로컬 개발은 가능하지만 프로덕션 배포에 필요합니다.${NC}"
fi

echo ""

# Create environment file
echo -e "${BLUE}🔧 환경 변수 설정 중...${NC}"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  기존 .env 파일이 있습니다. 백업 중...${NC}"
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
fi

echo "# WorkflowAI Environment Variables - Generated $(date)" > "$ENV_FILE"
echo "# Auto-generated by setup script" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Application Settings
echo "=== 기본 애플리케이션 설정 ===" 
echo ""

NEXT_PUBLIC_APP_URL=$(prompt_for_input "NEXT_PUBLIC_APP_URL" "애플리케이션 URL" "http://localhost:3000")
API_BASE_URL=$(prompt_for_input "API_BASE_URL" "백엔드 API URL" "http://localhost:8000")
ENVIRONMENT=$(prompt_for_input "ENVIRONMENT" "실행 환경" "development")

echo "" >> "$ENV_FILE"
echo "# === APPLICATION ===" >> "$ENV_FILE"
echo "NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL" >> "$ENV_FILE"
echo "API_BASE_URL=$API_BASE_URL" >> "$ENV_FILE"
echo "ENVIRONMENT=$ENVIRONMENT" >> "$ENV_FILE"
echo "LOG_LEVEL=info" >> "$ENV_FILE"

# Database Configuration
echo ""
echo -e "${PURPLE}📊 데이터베이스 설정${NC}"
echo "Supabase 프로젝트가 필요합니다: https://supabase.com"
echo ""

echo -e "${YELLOW}Supabase 대시보드에서 다음 정보를 가져와주세요:${NC}"
SUPABASE_URL=$(prompt_for_input "SUPABASE_URL" "Supabase Project URL" "" "^https://.*\.supabase\.co$")
SUPABASE_ANON_KEY=$(prompt_for_input "SUPABASE_ANON_KEY" "Supabase Anon Key")
SUPABASE_SERVICE_KEY=$(prompt_for_input "SUPABASE_SERVICE_KEY" "Supabase Service Role Key")

echo "" >> "$ENV_FILE"
echo "# === DATABASE ===" >> "$ENV_FILE"
echo "SUPABASE_URL=$SUPABASE_URL" >> "$ENV_FILE"
echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> "$ENV_FILE"
echo "SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY" >> "$ENV_FILE"
echo "DATABASE_URL=${SUPABASE_URL/https:\/\//postgres://postgres:[YOUR_PASSWORD]@}/postgres" >> "$ENV_FILE"

# Authentication (Clerk)
echo ""
echo -e "${PURPLE}🔐 인증 설정 (Clerk)${NC}"
echo "Clerk 대시보드: https://clerk.com"
echo ""

CLERK_SECRET_KEY=$(prompt_for_input "CLERK_SECRET_KEY" "Clerk Secret Key")
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$(prompt_for_input "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" "Clerk Publishable Key")

echo "" >> "$ENV_FILE"
echo "# === AUTHENTICATION ===" >> "$ENV_FILE"
echo "CLERK_SECRET_KEY=$CLERK_SECRET_KEY" >> "$ENV_FILE"
echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" >> "$ENV_FILE"
echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in" >> "$ENV_FILE"
echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up" >> "$ENV_FILE"
echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard" >> "$ENV_FILE"
echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard" >> "$ENV_FILE"

# AI APIs
echo ""
echo -e "${PURPLE}🤖 AI API 설정${NC}"
echo ""

echo -e "${YELLOW}OpenAI API Key (GPT-4, DALL-E):${NC}"
OPENAI_API_KEY=$(prompt_for_input "OPENAI_API_KEY" "OpenAI API Key" "" "^sk-")

echo -e "${YELLOW}Anthropic API Key (Claude):${NC}"
ANTHROPIC_API_KEY=$(prompt_for_input "ANTHROPIC_API_KEY" "Anthropic API Key")

echo -e "${YELLOW}Midjourney API Key (선택사항):${NC}"
read -r -p "Midjourney API Key (Enter로 건너뛰기): " MIDJOURNEY_API_KEY

echo "" >> "$ENV_FILE"
echo "# === AI APIS ===" >> "$ENV_FILE"
echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> "$ENV_FILE"
echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> "$ENV_FILE"
echo "MIDJOURNEY_API_KEY=$MIDJOURNEY_API_KEY" >> "$ENV_FILE"

# Payment (Stripe)
echo ""
echo -e "${PURPLE}💳 결제 설정 (Stripe)${NC}"
echo "Stripe 대시보드: https://dashboard.stripe.com"
echo ""

STRIPE_SECRET_KEY=$(prompt_for_input "STRIPE_SECRET_KEY" "Stripe Secret Key" "" "^sk_")
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(prompt_for_input "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" "Stripe Publishable Key" "" "^pk_")
STRIPE_WEBHOOK_SECRET=$(prompt_for_input "STRIPE_WEBHOOK_SECRET" "Stripe Webhook Secret")

echo "" >> "$ENV_FILE"
echo "# === PAYMENT ===" >> "$ENV_FILE"
echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> "$ENV_FILE"
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" >> "$ENV_FILE"
echo "STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET" >> "$ENV_FILE"

# Platform Integrations
echo ""
echo -e "${PURPLE}🔗 플랫폼 통합 설정${NC}"
echo ""

# GitHub
echo -e "${YELLOW}GitHub App 설정 (선택사항):${NC}"
read -r -p "GitHub App ID (Enter로 건너뛰기): " GITHUB_APP_ID
read -r -p "GitHub Client ID (Enter로 건너뛰기): " GITHUB_CLIENT_ID
read -r -p "GitHub Client Secret (Enter로 건너뛰기): " GITHUB_CLIENT_SECRET

# Figma
echo -e "${YELLOW}Figma 설정 (선택사항):${NC}"
read -r -p "Figma Client ID (Enter로 건너뛰기): " FIGMA_CLIENT_ID
read -r -p "Figma Client Secret (Enter로 건너뛰기): " FIGMA_CLIENT_SECRET

# Slack
echo -e "${YELLOW}Slack 설정 (선택사항):${NC}"
read -r -p "Slack Client ID (Enter로 건너뛰기): " SLACK_CLIENT_ID
read -r -p "Slack Client Secret (Enter로 건너뛰기): " SLACK_CLIENT_SECRET

echo "" >> "$ENV_FILE"
echo "# === PLATFORM INTEGRATIONS ===" >> "$ENV_FILE"
echo "GITHUB_APP_ID=$GITHUB_APP_ID" >> "$ENV_FILE"
echo "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID" >> "$ENV_FILE"
echo "GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET" >> "$ENV_FILE"
echo "FIGMA_CLIENT_ID=$FIGMA_CLIENT_ID" >> "$ENV_FILE"
echo "FIGMA_CLIENT_SECRET=$FIGMA_CLIENT_SECRET" >> "$ENV_FILE"
echo "SLACK_CLIENT_ID=$SLACK_CLIENT_ID" >> "$ENV_FILE"
echo "SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET" >> "$ENV_FILE"

# Generate secure keys
echo ""
echo -e "${BLUE}🔐 보안 키 생성 중...${NC}"

JWT_SECRET=$(generate_secret)
ENCRYPTION_KEY=$(generate_secret)

echo "" >> "$ENV_FILE"
echo "# === SECURITY ===" >> "$ENV_FILE"
echo "JWT_SECRET=$JWT_SECRET" >> "$ENV_FILE"
echo "ENCRYPTION_KEY=$ENCRYPTION_KEY" >> "$ENV_FILE"

# MCP Servers
echo "" >> "$ENV_FILE"
echo "# === MCP SERVERS ===" >> "$ENV_FILE"
echo "MCP_MARKETING_SERVER_URL=http://localhost:8001" >> "$ENV_FILE"
echo "MCP_DESIGN_SERVER_URL=http://localhost:8002" >> "$ENV_FILE"
echo "MCP_DEVELOPER_SERVER_URL=http://localhost:8003" >> "$ENV_FILE"

echo ""
echo -e "${GREEN}✅ 환경 변수 파일 생성 완료: $ENV_FILE${NC}"

# Install dependencies
echo ""
echo -e "${BLUE}📦 의존성 설치 중...${NC}"

echo "Frontend 의존성 설치..."
npm install
echo -e "${GREEN}✅ Frontend 의존성 설치 완료${NC}"

# Python backend setup
echo ""
echo "Backend Python 환경 설정..."
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    echo -e "${GREEN}✅ Python 가상환경 생성 완료${NC}"
fi

source "$VENV_DIR/bin/activate"
pip install --upgrade pip
pip install -r backend/requirements.txt
echo -e "${GREEN}✅ Backend 의존성 설치 완료${NC}"

# Database setup
echo ""
echo -e "${BLUE}🗄️  데이터베이스 설정${NC}"

if [ -f "database/schema.sql" ]; then
    echo -e "${YELLOW}데이터베이스 스키마를 Supabase에 적용하시겠습니까? (y/n)${NC}"
    read -r apply_schema
    
    if [[ $apply_schema =~ ^[Yy]$ ]]; then
        echo "Supabase CLI를 사용하여 스키마를 적용하세요:"
        echo "1. Supabase CLI 설치: npm install -g supabase"
        echo "2. 프로젝트 연결: supabase link --project-ref YOUR_PROJECT_ID"
        echo "3. 스키마 적용: supabase db push"
        echo ""
        echo "또는 Supabase 웹 대시보드에서 SQL 에디터를 사용하여 database/schema.sql 파일 내용을 실행하세요."
    fi
fi

# Create startup script
echo ""
echo -e "${BLUE}🚀 시작 스크립트 생성 중...${NC}"

cat > start-dev.sh << 'EOF'
#!/bin/bash

# WorkflowAI Development Startup Script

set -e

echo "🚀 WorkflowAI 개발 환경 시작 중..."

# Check if .env exists
if [ ! -f .env ]; then
    echo "❌ .env 파일이 없습니다. setup.sh를 먼저 실행해주세요."
    exit 1
fi

# Load environment variables
export $(grep -v '^#' .env | xargs)

# Start MCP servers in background
echo "🤖 MCP 서버 시작 중..."
./scripts/run_mcp_servers.sh start

# Wait for MCP servers to be ready
sleep 5

# Start backend in background
echo "🔧 백엔드 서버 시작 중..."
cd backend && python3 -m uvicorn main:app --reload --host 0.0.0.0 --port 8000 &
BACKEND_PID=$!
cd ..

# Wait for backend to be ready
sleep 3

# Start frontend
echo "🎨 프론트엔드 서버 시작 중..."
npm run dev &
FRONTEND_PID=$!

echo ""
echo "✅ 모든 서비스가 시작되었습니다!"
echo "   🎨 프론트엔드: http://localhost:3000"
echo "   🔧 백엔드 API: http://localhost:8000"
echo "   🤖 MCP 서버: 8001, 8002, 8003"
echo ""
echo "종료하려면 Ctrl+C를 누르세요."

# Wait for user interrupt
trap 'echo ""; echo "🛑 서비스 종료 중..."; kill $BACKEND_PID $FRONTEND_PID; ./scripts/run_mcp_servers.sh stop; exit 0' INT

wait
EOF

chmod +x start-dev.sh

echo -e "${GREEN}✅ 개발 시작 스크립트 생성: start-dev.sh${NC}"

# Create production docker-compose
cat > docker-compose.yml << 'EOF'
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - mcp-marketing
      - mcp-design
      - mcp-developer

  mcp-marketing:
    build:
      context: ./mcp-servers
      dockerfile: Dockerfile.marketing
    ports:
      - "8001:8001"
    env_file:
      - .env

  mcp-design:
    build:
      context: ./mcp-servers
      dockerfile: Dockerfile.design
    ports:
      - "8002:8002"
    env_file:
      - .env

  mcp-developer:
    build:
      context: ./mcp-servers
      dockerfile: Dockerfile.developer
    ports:
      - "8003:8003"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
EOF

echo -e "${GREEN}✅ Docker Compose 설정 파일 생성 완료${NC}"

# Final summary
echo ""
echo -e "${GREEN}🎉 WorkflowAI 환경 설정 완료!${NC}"
echo -e "${GREEN}==============================${NC}"
echo ""
echo -e "${BLUE}다음 단계:${NC}"
echo "1. 환경 변수 확인: cat .env"
echo "2. 개발 서버 시작: ./start-dev.sh"
echo "3. 브라우저 열기: http://localhost:3000"
echo ""
echo -e "${BLUE}유용한 명령어:${NC}"
echo "• MCP 서버 상태: ./scripts/run_mcp_servers.sh status"
echo "• MCP 서버 로그: ./scripts/run_mcp_servers.sh logs [server_name]"
echo "• 개발 서버 종료: Ctrl+C"
echo ""
echo -e "${YELLOW}📋 체크리스트:${NC}"
echo "□ Supabase 프로젝트 생성 및 스키마 적용"
echo "□ Clerk 프로젝트 설정"
echo "□ OpenAI API 키 획득"
echo "□ Stripe 계정 설정"
echo "□ 도메인 및 SSL 인증서 (프로덕션용)"
echo ""
echo -e "${GREEN}문제가 있으면 logs 폴더를 확인하거나 GitHub Issues에 문의하세요.${NC}"